import { createContext, useContext, useState, useEffect, type ReactNode } from 'react'

export type Language = 'fr' | 'en'

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string, params?: Record<string, string | number>) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

const STORAGE_KEY = 'palto-lang'

function readStoredLanguage(): Language | null {
  if (typeof window === 'undefined') return null
  const cur = localStorage.getItem(STORAGE_KEY) as Language | null
  if (cur === 'fr' || cur === 'en') return cur
  return null
}

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    if (typeof window === 'undefined') return 'fr'
    const stored = readStoredLanguage()
    if (stored) return stored
    // Détecter la langue du navigateur
    const browserLang = navigator.language?.slice(0, 2)
    return browserLang === 'en' ? 'en' : 'fr'
  })

  useEffect(() => {
    localStorage.setItem(STORAGE_KEY, language)
    document.documentElement.lang = language
  }, [language])

  const setLanguage = (lang: Language) => setLanguageState(lang)

  const t = (key: string, params?: Record<string, string | number>): string => {
    const translations = TRANSLATIONS[language]
    const keys = key.split('.')
    let value: unknown = translations
    for (const k of keys) {
      value = (value as Record<string, unknown>)?.[k]
    }
    let str = typeof value === 'string' ? value : key
    if (params) {
      Object.entries(params).forEach(([k, v]) => {
        str = str.replace(new RegExp(`\\{${k}\\}`, 'g'), String(v))
      })
    }
    return str
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const ctx = useContext(LanguageContext)
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider')
  return ctx
}

// Traductions
const TRANSLATIONS: Record<Language, Record<string, unknown>> = {
  fr: {
    nav: {
      contact: 'Contact',
    },
    geoPrompt: {
      title: 'Autoriser la localisation ?',
      body:
        'Palto peut centrer la carte et proposer des trajets autour de votre position sur La Réunion. Vous pouvez refuser : la saisie manuelle des adresses reste possible.',
      allow: 'Autoriser',
      later: 'Pas maintenant',
    },
    chauffeurGeo: {
      title: 'Visible sur les courses (page Go)',
      body:
        'Sur iPhone, appuyez sur le bouton, autorisez la position, puis réappuyez si vous venez des Réglages Safari. Sans envoi GPS, les passagers ne vous voient pas.',
      activate: 'Activer ma position',
      activeTitle: 'Position partagée',
      activeBody:
        'Votre dernière position reste visible environ 2 h sur la page Go, même si vous fermez le dashboard. Appuyez sur « Actualiser » pour la mettre à jour.',
      refresh: 'Actualiser ma localisation',
    },
    clientMeetDriver: {
      back: 'Retour',
      unavailable:
        'Cette vue est réservée aux passagers connectés avec une course « chauffeur sur place » en cours.',
    },
    hero: {
      title: 'Palto — des trajets clairs sur La Réunion, du départ à l’arrivée.',
      infos: 'En bref',
      services: 'Avec Palto',
      servicesDescription:
        'Carte, estimation temps et distance, course maintenant ou plus tard, puis mise en relation avec des chauffeurs partenaires.',
      footer: '© {year} Palto',
      homeFooterAria: 'Pied de page',
      homeFooterNavAria: 'Liens utiles',
      tagManagement: 'Réservation rapide',
      tagMaquette: 'Carte & itinéraire',
      tagVision: 'Instant ou planifié',
      tagDesignSystem: 'Chauffeurs à proximité',
      tagBranding: 'Suivi de course',
      tagConsultant: 'La Réunion',
      categoryApplication: 'Réservation',
      categoryApplicationWeb: 'App web',
      categorySiteWeb: 'Site',
      categoryLogo: 'Identité',
      categoryMotion: 'Motion',
      categoryPlv: 'Affichage',
      seoDiscover: 'Découvrez',
      seoGoDesc: 'Réserver une course moto-taxi sur l’île.',
      seoContactDesc: 'Écrire à l’équipe Palto.',
      seoAccountDesc: 'Profil passager et préférences.',
      seoDriverLink: 'Espace chauffeur',
      seoDriverDesc: 'Connexion ou inscription au tableau de bord.',
      orderRideTitle: 'Commandez une course',
      /** Titre de la barre supérieure type compte sur l’accueil */
      homeTopbarTitle: 'Palto',
      homeTopbarTitleNavAria: "Aller à l'accueil",
      topbarSignIn: 'Se connecter',
      topbarSignUp: "S'inscrire",
      topbarAuthAria: 'Compte passager',
      orderRideSubtitle: 'Indiquez votre départ et votre arrivée sur La Réunion.',
      pickupLabel: 'Localisation (départ)',
      destinationLabel: 'Destination',
      bookingSearch: 'Rechercher',
      mapLoading: 'Chargement de la carte…',
      mapUnavailable: 'Carte indisponible (service cartographique indisponible).',
      map3D: '3D',
      map2D: '2D',
      map3DEnterAria: 'Activer la vue en perspective avec le relief',
      map3DExitAria: 'Revenir à la vue du dessus',
      homeCity: 'La Réunion',
      homeCountrySuffix: ', France',
      homeDepartmentSelectAria: 'Choisir un département',
      homeTakeChargeNow: 'Prendre en charge maintenant',
      homePickupTimingLabel: 'Prise en charge',
      homeTimingNow: 'Maintenant',
      homeTimingLater: 'À planifier',
      homePickupLabel: 'Saisissez un lieu',
      homePickupPlaceholder: 'Adresse ou lieu de prise en charge',
      homeDestinationLabel: 'Saisissez votre destination',
      homeDestinationPlaceholder: "Adresse ou lieu d'arrivée",
      homeSeePrices: 'Voir les prix',
      homeSuggestionsTitle: 'Suggestions',
      chauffeurCtaTitle: 'Gérez vos courses simplement avec Palto.',
      chauffeurCtaSignIn: 'Se connecter',
      chauffeurCtaSignUp: 'Créer un compte',
      chauffeurBenefitsTitle: 'Avantages',
      chauffeurBenefit1: "Gestion de votre planning : créneaux, disponibilités et vue d'ensemble.",
      chauffeurBenefit2: 'Gestion de votre flotte : véhicules, équipes et suivi opérationnel.',
      chauffeurBenefit3: 'Gestion de vos dépenses et de vos revenus : indicateurs et synthèses.',
      destinationSpotlightBack: 'Retour',
      destinationSpotlightFlightTitle: 'Heures de vol (indicatif)',
      destinationSpotlightLead:
        'Estimation et commande en quelques clics. Les chauffeurs partenaires couvrent tout le territoire.',
      destinationSpotlightCta: 'Voir les prix et commander',
      destinationSpotlightBadge: 'Lieux populaires',
      destinationSpotlightContextTitle: 'Pour votre trajet',
      clientNextRideAria: 'Prochaine course programmée',
      clientNextRideLabel: 'Prochaine course',
      clientNextRideLink: 'Compte',
      clientLiveMeetCta: 'Rejoindre votre chauffeur',
      clientTopbarRidesAria: 'Courses et prise en charge',
      chauffeurLandingHeadlineLead: 'Pensé pour vous faire gagner du temps,',
      chauffeurLandingHeadlineAccent: 'Palto est la plateforme des chauffeurs à La Réunion.',
      chauffeurLandingSub:
        'Planning, courses et revenus au même endroit. Moto-taxis, VTC, livraisons : concentrez-vous sur la route.',
      chauffeurLandingCtaSignup: "S'inscrire",
      chauffeurLandingCtaSignin: 'Se connecter',
      chauffeurLandingLinkPassengers: 'Espace passagers',
      chauffeurLandingLinkBook: 'Commander une course',
      chauffeurLandingTrusted: 'Pensée pour les pros de la route',
      chauffeurLandingFeaturePlanningTitle: 'Votre journée, clarifiée',
      chauffeurLandingFeaturePlanningBody:
        'Créneaux, demandes et statuts : l’essentiel sans le bruit des messages.',
      chauffeurLandingFeatureFleetTitle: 'Flotte et équipe',
      chauffeurLandingFeatureFleetBody:
        'Véhicules, collaborateurs et organisation quand votre activité grandit.',
      chauffeurLandingFeatureMoneyTitle: 'Revenus et dépenses',
      chauffeurLandingFeatureMoneyBody:
        'Indicateurs simples pour suivre vos courses et votre activité dans le temps.',
      chauffeurLandingMockCaption: 'Aperçu du tableau de bord',
      chauffeurLandingMockTask1: 'Course Le Port → Saint-Denis',
      chauffeurLandingMockTask2: 'Document assurance à renouveler',
      chauffeurLandingMockTask3: 'Synthèse revenus de la semaine',
      chauffeurLandingMockPillLive: 'En cours',
      chauffeurLandingMockPillAction: 'Action',
      chauffeurLandingMockPillStats: 'Stats',
      chauffeurLandingTrustedTag1: 'La Réunion',
      chauffeurLandingTrustedTag2: 'Moto-taxi',
      chauffeurLandingTrustedTag3: 'VTC',
      chauffeurLandingTrustedTag4: 'Livraison',
      chauffeurLandingMatchEyebrow: 'Fini le bruit des messagers',
      chauffeurLandingMatchTitle: 'Une mise en relation claire, du premier message à la fin de course.',
      chauffeurLandingMatchLead:
        'Palto relie passagers et chauffeurs autour de la course : statut, lieux et détails utiles au même endroit. Plus besoin de jongler entre WhatsApp, Messenger et les SMS.',
      chauffeurLandingMatchPoint1:
        'Une demande structurée : qui, où, quand et quoi régler — sans fil de discussion qui s’éternise.',
      chauffeurLandingMatchPoint2:
        'Tout le monde voit la même vérité : moins de malentendus, moins de « tu m’as dit quoi ? ».',
      chauffeurLandingMatchPoint3:
        'Vous vous concentrez sur la route et le service ; Palto porte le contexte métier.',
      chauffeurLandingPlanningBadge: 'Planning intégré',
      chauffeurLandingPlanningTitle: 'Votre agenda, au cœur de l’activité',
      chauffeurLandingPlanningBody:
        'Créneaux, courses à venir et disponibilité lisibles d’un coup d’œil. Anticipez la journée sans calendrier séparé ni rappels éparpillés dans les messagers.',
      chauffeurLandingMatchVisualCaption: 'Un seul fil métier',
      chauffeurLandingClosingTitle: 'Roulez avec Palto.',
      chauffeurLandingClosingSub: 'Créez votre compte chauffeur et accédez au tableau de bord.',
    },
    search: {
      destinationPlaceholder: 'Indiquez votre destination',
      bookingSearch: 'Rechercher',
      bookingSearchLoading: 'Recherche…',
      bookingReserve: 'Réserver',
      bookingReserveLoading: 'Réservation…',
      bookingHintScheduled:
        'Renseignez le départ, la destination et l’heure, puis appuyez sur Réserver pour voir le récapitulatif.',
      bookingRecapConfirmScheduled: 'Finaliser la réservation',
      checkoutTitle: 'Paiement de la course',
      checkoutLead: 'Vérifiez le récapitulatif, puis validez votre commande.',
      checkoutLoggedInAs: 'Compte passager : {email}',
      checkoutStepsAria: 'Étapes de commande',
      checkoutStepInfo: 'Coordonnées',
      checkoutStepCard: 'Carte (test)',
      checkoutStripeLead:
        'Autorisation bancaire sans débit immédiat. Palto prélève {fee} € + le tarif chauffeur en fin de course. Annulation rapide : aucun frais.',
      checkoutStripeOff: 'Paiement en ligne non configuré : règlement prévu avec le chauffeur.',
      checkoutNameLabel: 'Nom (optionnel)',
      checkoutNamePlaceholder: 'Votre nom',
      checkoutEmailLabel: 'E-mail pour le suivi',
      checkoutEmailPlaceholder: 'vous@example.com',
      checkoutCommentLabel: 'Commentaire pour le chauffeur (optionnel)',
      checkoutCommentPlaceholder:
        'Ex. : l’entrée de mon bâtiment est derrière la poste.',
      checkoutCardLead: 'Saisissez une carte de test ci-dessous (mode test Stripe, aucun vrai débit).',
      checkoutAuthorizeCta: 'Autoriser le paiement sur la carte',
      checkoutContinuePayment: 'Continuer vers le paiement',
      checkoutPreparing: 'Préparation…',
      checkoutConfirmOrder: 'Confirmer la commande',
      checkoutDriverLabel: 'Chauffeur :',
      checkoutDriverLater: 'À confirmer par un chauffeur',
      checkoutVehicleLabel: 'Véhicule :',
      checkoutDriverFare: 'Tarif chauffeur (TTC) :',
      checkoutPaltoFee: 'Commission Palto :',
      checkoutTotalAuth: 'Total autorisé sur la carte :',
      checkoutTotalEstimate: 'Total estimé TTC :',
      checkoutTestCardAria: 'Carte bancaire de test Stripe',
      checkoutTestCardTitle: 'Mode test — carte fictive',
      checkoutTestCardLead:
        'Aucun argent réel n’est débité. Utilisez cette carte dans le champ ci-dessous :',
      checkoutTestCardCopy: 'Copier le numéro',
      checkoutTestCardCopied: 'Copié',
      checkoutTestCardExpiry: 'Date : n’importe quelle date future (ex. 12/34)',
      checkoutTestCardCvc: 'CVC : 3 chiffres quelconques (ex. 123)',
      goTimingNow: 'Partir maintenant',
      goTimingLater: 'Programmer le départ',
      goTimingPickerTitle: 'Quand partez-vous ?',
      goTimingPickerCloseAria: 'Fermer',
      popularPlacesTitle: 'Lieux les plus demandés',
      sectorsTitle: 'Sur l’île',
      chooseRideTitle: 'Choisissez une course',
      chooseRideSubtitle: 'Temps estimé et distance pour chaque chauffeur.',
      chooseRideRadiusLead: 'Chauffeurs disponibles dans un rayon de {km} km autour de votre départ.',
      editRideQuery: 'Modifier le trajet',
      goPreviousStep: 'Précédent',
      chooseDriverCta: 'Choisir ce chauffeur',
      chooseDriverHint: 'Sélectionnez un chauffeur pour continuer',
      driversLoading: 'Recherche de chauffeurs en ligne…',
      driversEmpty:
        'Aucun chauffeur disponible dans ce rayon. La position d’un chauffeur reste visible environ 2 h après sa dernière mise à jour (dashboard ou bouton « Actualiser ma localisation »).',
    },
    chauffeurAuth: {
      titleLogin: 'Connexion chauffeur',
      titleSignup: 'Créer un compte chauffeur',
      subtitleLogin: 'Accédez à votre tableau de bord, courses et organisation.',
      subtitleSignup:
        'Après inscription, vos courses restent bloquées tant que les pièces légales listées dans le tableau de bord ne sont pas fournies (cases à cocher sur cet appareil). Téléphone, type de véhicule et équipement livraison sont enregistrés sur cet appareil.',
      signupPhoneLabel: 'Téléphone',
      signupPhoneDial: 'Indicatif pays',
      signupPhonePlaceholder: 'Ex. 692 12 34 56',
      vehicleTypeLabel: 'Type de véhicule',
      vehicleBerline: 'Berline',
      vehicleUtilitaire: 'Utilitaire',
      vehicleMoto: 'Moto',
      vehicleScooter: 'Scooter',
      deliveryEquippedLabel: 'Je suis équipé pour la livraison',
      deliveryEquippedHint: '(caisson isotherme, sangles, etc.)',
      errorPhoneInvalid: 'Numéro de téléphone invalide pour l’indicatif choisi.',
      errorPhoneRequired: 'Téléphone obligatoire.',
      tabLogin: 'Connexion',
      tabSignup: 'Créer un compte',
      email: 'E-mail',
      password: 'Mot de passe',
      confirmPassword: 'Confirmer le mot de passe',
      submitLogin: 'Se connecter',
      submitSignup: 'Créer mon compte et me connecter',
      submittingLogin: 'Connexion…',
      submittingSignup: 'Création…',
      switchToSignup: 'Pas encore de compte ? Créer un compte',
      switchToLogin: 'Déjà un compte ? Se connecter',
      backToSite: 'Retour au site',
      footerLegal:
        'En continuant, vous reconnaissez avoir pris connaissance des conditions d’utilisation et de la politique de confidentialité de Palto.',
      errorGeneric: 'Une erreur est survenue. Réessayez.',
      errorEmailUsed: 'Cette adresse e-mail est déjà enregistrée sur cet appareil.',
      errorEmailReserved:
        'Cette adresse correspond au compte administrateur principal : utilisez « Connexion » ou une autre adresse.',
      errorPasswordShort: 'Le mot de passe doit contenir au moins 6 caractères.',
      errorPasswordMismatch: 'Les mots de passe ne correspondent pas.',
      errorInvalidEmail: 'Adresse e-mail invalide.',
    },
    chauffeurCompliance: {
      bannerTitle: 'Documents légaux requis',
      bannerLead:
        'En tant que chauffeur inscrit sur cet appareil, vous devez fournir les pièces ci-dessous avant d’accepter ou de lancer des courses. Cochez chaque ligne une fois le justificatif déposé (simulation locale).',
      checklistLead: 'Cochez chaque document dès qu’il est fourni (contrôle réel à brancher côté serveur).',
      checklistAria: 'Liste des documents obligatoires',
      allProvided: 'Tous les documents sont indiqués comme fournis — les courses sont débloquées.',
      complianceUploadHint:
        'Aucun fichier n’est envoyé ici ; l’intégration KYC / upload sécurisé est à prévoir en production.',
      doc_driving_license: 'Permis de conduire (catégorie adaptée)',
      doc_vtc_or_goods_capacity:
        'Carte professionnelle VTC ou droit d’exercer — ou attestation de capacité de transport de marchandises',
      doc_digital_identity: 'Identité numérique / pièce d’identité officielle',
      doc_kbis_siret: 'KBIS ou numéro SIRET (entreprise / auto-entrepreneur)',
      doc_security_declaration: 'Justificatif sécurité / registre (selon votre statut)',
      doc_rc_pro: 'Responsabilité civile professionnelle (RC Pro)',
      doc_insurance_civil_pro: 'Attestations assurance civile et professionnelle',
      doc_vehicle_insurance: 'Assurance du véhicule utilisé',
    },
    clientAuth: {
      titleLogin: 'Connexion passager',
      titleSignup: 'Créer un compte passager',
      subtitleLogin: 'Accédez à votre compte, courses et préférences.',
      subtitleSignup:
        'Compte enregistré sur cet appareil. Vos données « Mon compte » restent locales sur ce navigateur.',
      tabLogin: 'Connexion',
      tabSignup: 'Créer un compte',
      email: 'E-mail',
      password: 'Mot de passe',
      confirmPassword: 'Confirmer le mot de passe',
      submitLogin: 'Se connecter',
      submitSignup: 'Créer mon compte et me connecter',
      submittingLogin: 'Connexion…',
      submittingSignup: 'Création…',
      switchToSignup: 'Pas encore de compte ? Créer un compte',
      switchToLogin: 'Déjà un compte ? Se connecter',
      backToSite: 'Retour au site',
      footerLegal:
        'En continuant, vous reconnaissez avoir pris connaissance des conditions d’utilisation et de la politique de confidentialité de Palto.',
      errorGeneric: 'Une erreur est survenue. Réessayez.',
      errorEmailUsed: 'Cette adresse e-mail est déjà enregistrée sur cet appareil.',
      errorEmailReserved:
        'Cette adresse correspond au compte passager principal réservé : utilisez « Connexion » ou une autre adresse.',
      errorPasswordShort: 'Le mot de passe doit contenir au moins 6 caractères.',
      errorPasswordMismatch: 'Les mots de passe ne correspondent pas.',
      errorInvalidEmail: 'Adresse e-mail invalide.',
    },
    error: {
      pageNotFound: 'Page non trouvée',
      pageNotFoundMessage: 'La page que vous recherchez n’existe pas ou a été déplacée.',
      backToHome: "Retour à l'accueil",
      discoverProjects: 'Réserver une course',
    },
    project: {
      context:
        'Go est l’interface Palto pour commander une course : départ et arrivée sur La Réunion, carte interactive, estimation temps et distance, course immédiate ou planifiée, puis confirmation.',
      objectives: 'Objectifs produit',
      team: 'Acteurs',
      myRole: 'Rôle de l’interface',
      role: 'RÔLE',
      name: 'LIBELLÉ',
      tocSummary: 'Vue d’ensemble',
      tocTeam: 'Acteurs',
      caseStudie: 'Parcours & interface',
      ideation: 'Parcours envisagés',
      implementation: 'Intégration & stack',
      results: 'Suivi & prochaines étapes',
      problematique: 'Besoin utilisateur',
      solution: 'Réponse Palto',
      process: 'Méthode',
      processIntro:
        'Le parcours a été cadré autour des trajets réels sur l’île, des contraintes de circulation et du besoin de clarté entre course immédiate et course programmée.',
      processSummary:
        'Itérations sur prototypes : recherche d’adresses, affichage des chauffeurs à proximité, tracé d’itinéraire et étapes de validation avant envoi de la demande de course.',
      audit: 'Recherche & usages',
      architecture: 'Architecture fonctionnelle',
      userFlow: 'Parcours utilisateur',
      designSystem: 'Système d’interface',
      dsTabCarousel: 'Description',
      dsTabPalette: 'Palette',
      dsTabTypescale: 'Typéchelle',
      palette: 'Palette',
      materialDesign: '(Material Design)',
      roleToken: 'Rôle (Token)',
      usage: 'Usage / Fonction',
      hexValue: 'Valeur Hex',
      typescale: 'Typescale',
      baseValue: 'Base Value: 16',
      roleCol: 'Rôle',
      typography: 'Typographie',
      size: 'Taille',
      lineHeight: 'Interlignage',
      example: 'Exemple',
      conception: 'Conception & itérations',
      integration: 'Intégration & déploiement',
      otherProjects: 'Continuer sur Palto',
      whatNext: 'Prochaines étapes',
      backToTop: 'Retourner en haut',
      backHome: "Retour à l'accueil",
      viewProject: 'Voir le détail Go',
      contactMe: 'Nous contacter',
      auditLead:
        'Analyse des usages de mobilité locale : départ précis, doute sur l’horaire, besoin de repères carte + texte pour l’arrivée, et lecture rapide sur mobile.',
      auditBody:
        'Synthèse des patterns utiles : formulaire lisible, suggestions d’adresses, états de chargement explicites, erreurs actionnables et récapitulatif clair avant confirmation.',
      archLead:
        'Modèle centré sur la course : origine, destination, créneau, statut (brouillon / demandée / acceptée), chauffeur lié, estimations cartographiques pour temps et distance.',
      archBody:
        'Les écrans séparent les responsabilités : saisie des lieux, carte et itinéraire, choix du mode (maintenant / plus tard), étape chauffeurs puis envoi — pour faciliter l’évolution côté API.',
      conceptionLead1:
        'Priorité mobile et lisibilité en situation réelle : contrastes renforcés, zones tactiles confortables et libellés courts sur les étapes clés.',
      conceptionLead2:
        'Plusieurs itérations sur le fil de réservation pour limiter les allers-retours entre carte, champs d’adresse et récapitulatif.',
      conceptionCaption1:
        'Barre supérieure sobre : accueil, contact, compte et accès chauffeur — sans distraire de la réservation.',
      conceptionCaption2:
        'Zone d’actions principale proche du formulaire : recherche de trajet, choix du mode de course, passage à l’étape suivante.',
      conceptionCaption3:
        'Alignement de la charte Palto avec la lisibilité sur fond carte et les thèmes clair / sombre.',
      conceptionCaption4:
        'Contrôle des combinaisons couleur / texte sur cartes et badges de statut ; hiérarchie typographique pour distinguer estimation, montant indicatif et action principale.',
      contrastTitle: 'Contrôle lisibilité & contraste',
      contrastImageAlt: 'Go — réservation, interface en mode clair',
      lightModeSinglePageAlt: 'Go — récapitulatif parcours',
      lightModeSetp1Alt: 'Go — choix chauffeur, étape 1',
      integrationTitle:
        'Déploiement progressif : l’interface évolue sans friction ; l’activation API + Supabase permet la persistance des courses et les actions côté chauffeur.',
      integrationLead:
        'Composants isolés (carte, liste chauffeurs, récap) pour faire évoluer règles métier, paiement hors ligne pour l’instant, puis notifications et suivi avancé.',
      december2023: 'Recherche & cadrage',
      february2025: 'Interface Go stabilisée',
      auditAlt1: 'Usages — mobilité locale 1',
      auditAlt2: 'Usages — mobilité locale 2',
      auditAlt3: 'Usages — mobilité locale 3',
      auditAlt4: 'Usages — mobilité locale 4',
      /** Graduations galerie Conception & Itération (page projet) */
      conceptGraduationLabel: 'Étape {n}',
      conceptionGraduationGroup: 'Parcours réservation',
      conceptionStageAlt: 'Étape {concept} — vue {slide}',
      conceptionVerticalCarousel: 'Vues de l’étape sélectionnée',
      cardSwapAria: 'Aperçu animé — parcours Palto Go',
      integrationAlt: 'Intégration technique',
      wireframeAlt: 'Wireframe — parcours réservation Palto',
      maquetteAlt: 'Maquette — écran réservation Palto',
      axisHorizontal: 'Axe horizontal',
      axisVertical: 'Axe vertical',
    },
    driverDashboard: {
      titleOverview: "Vue d'ensemble",
      titleCourses: 'Courses',
      titleStats: 'Statistiques',
      titleClients: 'Clients',
      titlePlanning: 'Planning',
      titleUser: 'Compte chauffeur',
      titleSettings: 'Réglages',
      titleHelp: 'Aide',
      navOverview: "Vue d'ensemble",
      navCourses: 'Courses',
      navStats: 'Statistiques',
      navClients: 'Clients',
      navPlanning: 'Planning',
      navUser: 'Compte',
      navSettings: 'Réglages',
      navHelp: 'Aide',
      navOrganization: 'Organisation',
      titleOrganization: 'Mon organisation',
      helpLead: 'Raccourcis et réponses courantes pour le tableau de bord chauffeur.',
      settingsMoreHint:
        'Ces préférences sont les mêmes que sur le site (compte passager) : elles s’appliquent à tout Palto sur cet appareil.',
      mainSubtitle: 'Vos courses, votre planning et votre activité au même endroit.',
      statsSubtitle: 'Vue rapide et lisible de ton activité chauffeur.',
      statsHeatmapPlaceholder:
        'Heatmap annuelle et résumés (jour le plus actif, séries) seront affichés lorsque l’API statistiques sera connectée. Les indicateurs du haut restent calculés sur tes courses locales.',
      orgPageLead:
        'Gérez votre flotte localement sur cet appareil. Les invitations sont simulées — branchement API à prévoir.',
      orgFleetCode: 'Code flotte',
      orgBase: 'Base',
      orgAdminEmail: 'Administrateur',
      orgCreated: 'Créée le',
      orgMembersTitle: 'Membres',
      orgInviteLabel: 'Inviter un chauffeur (e-mail)',
      orgInvitePlaceholder: 'chauffeur@exemple.re',
      orgInviteButton: 'Envoyer l’invitation',
      orgInviteInvalid: 'Indiquez une adresse e-mail valide.',
      orgInviteDuplicate: 'Cette adresse est déjà invitée ou membre.',
      orgInviteSelf: 'Vous ne pouvez pas vous inviter vous-même.',
      orgStatusPending: 'Invitation envoyée',
      orgStatusActive: 'Actif',
      orgRoleAdmin: 'Administrateur',
      orgRoleDriver: 'Chauffeur',
      orgRemoveInvite: 'Retirer',
      orgDeleteOrg: 'Supprimer l’organisation',
      orgDeleteConfirm:
        'Supprimer cette organisation ? Les données locales seront effacées ; l’entrée de menu disparaîtra.',
      orgSectionTitle: 'Organisation',
      orgNoOrgHint:
        'Créez une organisation pour devenir administrateur, obtenir un code flotte et inviter d’autres chauffeurs. L’entrée « Organisation » apparaîtra dans le menu latéral.',
      orgNoOrgSoonLabel: 'Bientôt disponible',
      orgCreateName: 'Nom de l’organisation',
      orgCreateBase: 'Base / zone',
      orgCreateButton: 'Créer l’organisation',
      orgOpenOrganization: 'Ouvrir la page Organisation',
      orgNameRequired: 'Le nom de l’organisation est obligatoire.',
      orgModeOrgLabel: 'Flotte',
      orgNavTeam: 'Équipe',
      orgNavFleet: 'Flotte',
      orgNavInvites: 'Invitations',
      orgNavSettings: 'Paramètres',
      orgProfileCoverAlt: 'Visuel de couverture de la flotte',
      orgProfileLogoAlt: 'Logo de la flotte',
      orgProfileImportantTitle: 'Infos clés',
      orgProfileDriversLabel: 'Chauffeurs actifs',
      orgProfileRatingLabel: 'Note moyenne',
      orgProfileRatingSuffix: 'avis',
      orgProfileReviewsTitle: 'Derniers avis',
      orgProfileReviewsLead: 'Exemples illustratifs — branchement avis clients à prévoir.',
      orgProfileReview1Author: 'Marie L.',
      orgProfileReview1Body:
        'Chauffeur ponctuel, trajet impeccable. Je recommande cette flotte pour les courses en ville.',
      orgProfileReview2Author: 'Karim D.',
      orgProfileReview2Body: 'Très professionnel, SMS de suivi clairs pour mon rendez-vous médical.',
      orgProfileReview3Author: 'Sophie P.',
      orgProfileReview3Body: 'Parfait pour l’aéroport : véhicule propre, conduite souple, bagages aidés.',
      orgReviewsPrev: 'Avis précédent',
      orgReviewsNext: 'Avis suivant',
      orgReviewsDots: 'Navigation des avis',
      orgReviewsGoTo: 'Aller à l’avis {n}',
      orgInviteNotifTitle: 'Invitation flotte · {org}',
      orgInviteNotifDesc:
        'Code flotte {code} · Invitation envoyée par {from}. Rejoignez la flotte depuis votre compte.',
      notificationsModalTitle: 'Toutes les notifications',
      notificationsSeeAll: 'Voir tout',
      moreMenuAria: "Plus d'options",
      moreMenuTitle: 'Options',
      reportBug: 'Signaler un bug',
      bugModalTitle: 'Signaler un bug',
      bugModalLead:
        'Un pouce vers le haut ou le bas pour indiquer si tout va bien ou si quelque chose bloque, puis décrivez le problème.',
      bugSentimentLabel: 'Votre ressenti sur cet écran',
      bugMessageLabel: 'Description du bug',
      bugMessagePlaceholder: 'Étapes pour reproduire, message d’erreur, navigateur…',
      bugSubmit: 'Envoyer',
      bugSubmitting: 'Envoi…',
      bugClose: 'Fermer',
      bugToastOk: 'Signalement envoyé. Merci !',
      bugToastErr: "L'envoi a échoué. Réessayez plus tard.",
      bugValidation: 'Décrivez le problème avant d’envoyer.',
      bugEmailMissing: 'Ajoutez un e-mail dans votre profil chauffeur pour envoyer un signalement.',
      orgSettingsDangerLead:
        'Zone sensible : la suppression efface la flotte, les membres et les invitations enregistrés sur cet appareil.',
      fleetTitle: 'Gestion de flotte',
      fleetLead:
        'Secteurs (Ouest, Sud, Est, Nord, Cilaos, etc.), véhicules et disponibilité — données locales sur cet appareil. À brancher sur votre outil métier ou API plus tard.',
      fleetFilterLabel: 'Filtrer par secteur',
      fleetFilterAll: 'Tous les secteurs',
      fleetSummaryTitle: 'Répartition (chauffeurs actifs)',
      fleetColMember: 'Membre',
      fleetColVehicle: 'Immatriculation',
      fleetColModel: 'Véhicule',
      fleetColZone: 'Secteur',
      fleetColAvail: 'Dispo.',
      fleetHintPending: 'Invitation en attente — affectation complète une fois le compte actif.',
      fleetPlatePlaceholder: 'ex. AA-123-BB',
      fleetModelPlaceholder: 'ex. Berline, scooter…',
      fleetDuplicatePlate: 'Cette immatriculation est déjà attribuée à un autre membre actif.',
      fleetZoneUnset: 'Non assigné',
      fleetZoneWest: 'Ouest',
      fleetZoneSouth: 'Sud',
      fleetZoneEast: 'Est',
      fleetZoneNorth: 'Nord',
      fleetZoneCilaos: 'Cilaos',
      fleetZoneCircus: 'Cirques',
      fleetZonePlainCafres: 'Plaine des Cafres',
      fleetZoneStPaul: 'Saint-Paul',
      fleetAvailAvailable: 'Disponible',
      fleetAvailOnCourse: 'En course',
      fleetAvailPause: 'Pause',
      fleetAvailOff: 'Hors ligne',
    },
    clientAccount: {
      title: 'Mon compte',
      lead: 'Informations utilisées pour vos courses et votre contact avec les chauffeurs Palto. Données enregistrées sur cet appareil.',
      navOverview: "Vue d'ensemble",
      navPersonalInfo: 'Informations personnelles',
      navSecurity: 'Sécurité',
      navPrivacy: 'Confidentialité et données',
      navSettings: 'Réglages',
      navHelp: 'Aides',
      navBackSite: "Retour au site",
      navBackOverview: 'Retour',
      navBackOverviewAria: "Retour à la vue d'ensemble du compte",
      navSignOut: 'Déconnexion',
      sectionPlaceholder: 'Contenu à venir pour cette section.',
      expandNav: 'Étendre la navigation',
      collapseNav: 'Réduire la navigation',
      closeMenu: 'Fermer le menu',
      openMenu: 'Ouvrir le menu',
      mobileActions: 'Actions compte',
      profileSection: 'Profil client',
      edit: 'Modifier',
      photoAlt: 'Photo de profil',
      changeProfilePhotoAria: 'Changer la photo de profil',
      photoReadError: 'Impossible de lire cette image. Essayez un autre fichier (JPEG ou PNG).',
      photoStorageError:
        'Enregistrement impossible (stockage plein). Essayez une image plus petite ou libérez de l’espace sur l’appareil.',
      statusActive: 'Actif',
      firstName: 'Prénom',
      lastName: 'Nom',
      email: 'Email',
      phone: 'Téléphone',
      city: 'Ville',
      status: 'Statut',
      preferenceTitle: 'Préférence de paiement',
      preferenceHint: 'Indiquez comment vous souhaitez payer en priorité ; le chauffeur peut proposer une alternative selon la course.',
      prefIndifferent: 'Indifférent',
      prefCard: 'Carte',
      prefCash: 'Espèces',
      save: 'Enregistrer',
      cancel: 'Annuler',
      recentTitle: 'Courses récentes',
      recentRidesCaption: 'Historique local sur cet appareil.',
      bookRide: 'Commander une course',
      rideDetailTitle: 'Récapitulatif de la course',
      rideDetailClose: 'Fermer',
      rideDepart: 'Départ',
      rideArrive: 'Arrivée',
      rideDate: 'Date',
      rideDepartTime: 'Heure de prise en charge',
      rideArriveTime: 'Heure d’arrivée estimée',
      rideDuration: 'Durée',
      rideDistance: 'Distance',
      ridePrice: 'Montant',
      rideDriver: 'Chauffeur',
      rideVehicle: 'Véhicule',
      ridePayment: 'Paiement',
      rideReference: 'Référence',
      rideStatus: 'Statut',
      rideDurationMinutes: '{n} min',
      rideDistanceKm: '{n} km',
      ridePriceEur: '{n} €',
      rideMeetTitle: 'Votre chauffeur vous attend',
      rideMeetLead:
        'Rendez-vous au point de prise en charge ci-dessous. Repérez le véhicule grâce au modèle, à la couleur et à la plaque.',
      rideMeetPickup: 'Lieu de prise en charge',
      rideMeetPickupTime: 'Prise en charge vers',
      rideMeetVehicleColor: 'Couleur :',
      rideMeetCall: 'Appeler le chauffeur',
      rideMeetCallDisabledHint: 'Indisponible pour le moment',
      rideMeetCta: 'J’ai rejoint mon chauffeur',
      rideMeetConfirmed: 'C’est noté',
      rideMeetToast: 'Merci ! Bon trajet avec Palto.',
      rideMeetDriverCardAria: 'Informations sur le chauffeur et le véhicule',
      rideMeetLocationTitle: 'Position du chauffeur',
      rideMeetLocationLive: 'Temps réel',
      rideMeetLocationAria: 'Localisation du chauffeur par rapport au lieu de prise en charge',
      rideMeetDistanceMeters: '≈ {m} m du point de prise en charge',
      rideMeetMapNoToken:
        'Sans service cartographique disponible, la carte ne s’affiche pas ici. La distance se met à jour quand même.',
      rideMeetDriverPin: 'Chauffeur',
      rideMeetClientPin: 'Vous',
      rideEndTitle: 'Fin de course',
      rideEndLead: 'Course {route} avec {driver}. Vérifiez le montant, le temps et la distance, puis laissez un avis.',
      rideEndStatsAria: 'Montant, distance et durée de la course',
      rideEndCashTitle: 'Règlement en espèces',
      rideEndCashHint:
        'Pour le moment, seul le paiement en espèces est prévu sur cette vue. Préparez la monnaie exacte si possible.',
      rideEndCashConfirm: 'Je confirme avoir réglé {amount} au chauffeur en espèces.',
      rideEndReviewTitle: 'Votre avis',
      rideEndReviewHint:
        'Note et commentaire sont une simulation : rien n’est envoyé au serveur pour le moment.',
      rideEndStarsAria: 'Note sur 5',
      rideEndStarLabel: 'Noter {n} sur 5',
      rideEndCommentLabel: 'Commentaire (optionnel)',
      rideEndCommentPlaceholder: 'Accueil, conduite, ponctualité…',
      rideEndSubmit: 'Envoyer mon avis',
      rideEndThanks: 'Merci pour votre retour !',
      personalHint: 'Modifiez vos informations ci-dessous, puis enregistrez.',
      overviewProfileHint:
        'Pour modifier vos données ou votre photo, utilisez « Informations personnelles » dans le menu.',
      overviewCoursesHint:
        'Le récapitulatif de toutes vos courses se trouve dans l’onglet « Mes courses » du menu.',
      navCourses: 'Mes courses',
      navPlaces: 'Lieux enregistrés',
      navWallet: 'Portefeuille',
      walletLead:
        'Consultez votre solde et votre historique d’activité. Les montants sont stockés localement sur cet appareil (aucune transaction réelle).',
      walletBalanceTitle: 'Solde disponible',
      walletActivityNote:
        'Les mouvements ci-dessous sont fictifs ; seul le solde peut être mis à jour via la simulation de recharge.',
      walletMovementsTitle: 'Derniers mouvements',
      walletSimulateTopup: 'Simuler une recharge (+5,00 €)',
      walletMov1: 'Course · Le Port → Saint-Denis',
      walletMov2: 'Recharge portefeuille (simulation)',
      walletMov3: 'Course · Saint-Pierre → Étang-Salé',
      walletOpen: 'Gérer le portefeuille',
      overviewWalletHint: 'Solde actuel : {balance}. Recharges et détail dans l’onglet Portefeuille.',
      coursesRecapTitle: 'Récapitulatif des courses',
      coursesRecapLead: 'Liste de toutes vos courses enregistrées sur cet appareil.',
      coursesEmptyHint: "Vous n'avez pas encore commandé de course.",
      securityPasswordTitle: 'Mot de passe',
      securityPasswordField: 'Mot de passe actuel',
      securityLastChanged: 'Dernière modification le {date}',
      securityChangePassword: 'Changer le mot de passe',
      securityNewPassword: 'Nouveau mot de passe',
      securityConfirmPassword: 'Confirmer le mot de passe',
      securitySavePassword: 'Enregistrer le nouveau mot de passe',
      securityCancel: 'Annuler',
      securityPasswordMismatch: 'Les mots de passe ne correspondent pas.',
      securityPasswordTooShort: 'Au moins 8 caractères.',
      securityOAuthTitle: 'Connexions sociales',
      securityOAuthGoogle: 'Google',
      securityOAuthFacebook: 'Facebook',
      securityOAuthApple: 'Apple',
      securityOAuthConnect: 'Connecter',
      securityOAuthDisconnect: 'Déconnecter',
      securityOAuthConnected: 'Connecté',
      securityOAuthNotConnected: 'Non connecté',
      settingsLead: 'Personnalisez l’affichage et le comportement de l’application sur cet appareil.',
      settingsLanguageTitle: 'Langue',
      settingsLanguageHint: 'Choisissez la langue des textes du compte et du site.',
      settingsAppearanceTitle: 'Apparence',
      settingsAppearanceHint:
        'Le mode sombre applique les couleurs définies pour tout le site (attribut data-app-theme sur la page).',
      settingsDarkMode: 'Mode sombre',
      settingsTextSizeTitle: 'Taille du texte',
      settingsTextSizeHint:
        '100 % = taille habituelle du site. Déplacez le curseur vers la droite pour agrandir tout l’affichage (textes en pixels inclus). Impossible de réduire en dessous du normal. Enregistré sur cet appareil.',
      settingsTextSizeAria: 'Taille du texte du site',
      settingsTextSizeValue: '{n} %',
      settingsNotificationsTitle: 'Notifications',
      settingsNotificationsHint:
        'Canaux pour rappels et messages liés à vos courses (aucun envoi réel pour le moment ; préférences enregistrées sur cet appareil).',
      settingsNotifyEmail: 'E-mail',
      settingsNotifySms: 'SMS',
      settingsNotifyPush: 'Notifications push',
      settingsMoreHint: 'D’autres réglages (accessibilité, etc.) pourront compléter cette page.',
      helpLead: 'Questions fréquentes et pistes pour obtenir de l’aide.',
      helpFaq1Q: 'Comment sont enregistrées mes données dans ce compte ?',
      helpFaq1A:
        'Profil, sécurité et portefeuille sont stockés localement dans votre navigateur. Aucune synchronisation serveur pour ces écrans.',
      helpFaq2Q: 'Comment consulter mes courses ?',
      helpFaq2A:
        'Ouvrez l’onglet « Mes courses », puis touchez une ligne pour afficher le récapitulatif détaillé. Les courses affichées sont fictives.',
      helpFaq3Q: 'Le solde du portefeuille est-il réel ?',
      helpFaq3A:
        'Non : il s’agit d’une simulation locale. Le bouton « Simuler une recharge » augmente uniquement le solde fictif sur cet appareil.',
      helpContactHint:
        'Pour nous contacter, utilisez la page Contact du site Palto (menu ou pied de page depuis l’accueil).',
      placesLead:
        'Enregistrez vos adresses habituelles pour remplir plus vite le départ ou l’arrivée sur une course. Données stockées sur cet appareil.',
      placesHome: 'Domicile',
      placesWork: 'Travail',
      placesAddressLabel: 'Adresse',
      placesAddressPlaceholder: 'Rue, lieu-dit, quartier, ville…',
      placesExtrasTitle: 'Autres lieux',
      placesExtraLabel: 'Nom du lieu',
      placesAddExtra: 'Ajouter un lieu',
      placesRemoveExtra: 'Retirer',
      placesSave: 'Enregistrer les lieux',
      placesOverviewHint: 'Domicile, travail et favoris pour vos prochaines courses.',
      placesOverviewOpen: 'Gérer les lieux',
      placesNoExtras: 'Aucun lieu supplémentaire. Utilisez « Ajouter un lieu » pour en enregistrer (ex. sport, famille).',
      placesSuggestionsAria: 'Suggestions d’adresse',
      placesSuggestionsPopular: 'Lieux fréquents',
      placesSuggestionsAddresses: 'Adresses (recherche)',
      placesSuggestionsLoading: 'Recherche…',
      placesSuggestionsMinChars: 'Tapez au moins 3 caractères pour obtenir des suggestions.',
      placesSuggestionsEmpty: 'Aucune adresse trouvée.',
      placesMarkOnMap: 'Marquer sur la carte',
      placesCoordsSaved: 'Position enregistrée',
      placesNoMapToken: 'Carte et suggestions indisponibles (service cartographique indisponible).',
      placesMapModalTitle: 'Choisir sur la carte',
      placesMapModalHint: 'Touchez la carte pour déplacer le repère sur la route la plus proche, puis validez.',
      placesMapConfirm: 'Valider cette position',
      placesMapCancel: 'Annuler',
      placesOutsideReunion: 'Choisissez un point sur l’île de La Réunion.',
      placesMapSnapFail: 'Impossible d’accrocher ce point à une route (réessayez plus près d’une route).',
      placesGeocodeError: 'Erreur lors de la lecture de l’adresse. Réessayez.',
      placesMapConfirming: 'Enregistrement…',
    },
  },
  en: {
    nav: {
      contact: 'Contact',
    },
    geoPrompt: {
      title: 'Allow location?',
      body:
        'Palto can center the map and suggest rides near you in Réunion. You can decline — typing addresses manually still works.',
      allow: 'Allow',
      later: 'Not now',
    },
    chauffeurGeo: {
      title: 'Visible for nearby rides (Go page)',
      body:
        'On iPhone, tap the button, allow location, then tap again if you just changed Safari settings. Without GPS, passengers will not see you nearby.',
      activate: 'Enable my location',
      activeTitle: 'Location shared',
      activeBody:
        'Your last position stays visible on the Go page for about 2 hours, even if you close the dashboard. Tap « Update » to refresh it.',
      refresh: 'Update my location',
    },
    clientMeetDriver: {
      back: 'Back',
      unavailable:
        'This screen is for signed-in passengers with a “driver waiting” ride in progress.',
    },
    hero: {
      title: 'Palto — clear rides across Réunion, from pickup to drop-off.',
      infos: 'At a glance',
      services: 'With Palto',
      servicesDescription:
        'Map, time and distance estimates, ride now or schedule later, then connect with partner drivers.',
      footer: '© {year} Palto',
      homeFooterAria: 'Footer',
      homeFooterNavAria: 'Useful links',
      tagManagement: 'Quick booking',
      tagMaquette: 'Map & route',
      tagVision: 'Instant or scheduled',
      tagDesignSystem: 'Nearby drivers',
      tagBranding: 'Ride tracking',
      tagConsultant: 'Réunion Island',
      categoryApplication: 'Booking',
      categoryApplicationWeb: 'Web app',
      categorySiteWeb: 'Website',
      categoryLogo: 'Brand',
      categoryMotion: 'Motion',
      categoryPlv: 'Display',
      seoDiscover: 'Discover',
      seoGoDesc: 'Book a moto-taxi ride on the island.',
      seoContactDesc: 'Message the Palto team.',
      seoAccountDesc: 'Passenger profile and preferences.',
      seoDriverLink: 'Driver area',
      seoDriverDesc: 'Sign in or create an account for the dashboard.',
      orderRideTitle: 'Book a ride',
      homeTopbarTitle: 'Palto',
      homeTopbarTitleNavAria: 'Go to home',
      topbarSignIn: 'Sign in',
      topbarSignUp: 'Sign up',
      topbarAuthAria: 'Passenger account',
      orderRideSubtitle: 'Enter your pickup and drop-off on Réunion Island.',
      pickupLabel: 'Pickup location',
      destinationLabel: 'Destination',
      bookingSearch: 'Search',
      mapLoading: 'Loading map…',
      mapUnavailable: 'Map unavailable (mapping service unavailable).',
      map3D: '3D',
      map2D: '2D',
      map3DEnterAria: 'Enable tilted map view with terrain',
      map3DExitAria: 'Return to flat top-down view',
      homeCity: 'Réunion Island',
      homeCountrySuffix: ', FR',
      homeDepartmentSelectAria: 'Choose a department',
      homeTakeChargeNow: 'Pickup now',
      homePickupTimingLabel: 'Pickup',
      homeTimingNow: 'Now',
      homeTimingLater: 'Schedule',
      homePickupLabel: 'Enter a pickup location',
      homePickupPlaceholder: 'Address or pickup point',
      homeDestinationLabel: 'Enter your destination',
      homeDestinationPlaceholder: 'Address or drop-off',
      homeSeePrices: 'See prices',
      homeSuggestionsTitle: 'Suggestions',
      chauffeurCtaTitle: 'Manage your rides easily with Palto.',
      chauffeurCtaSignIn: 'Sign in',
      chauffeurCtaSignUp: 'Create an account',
      chauffeurBenefitsTitle: 'Benefits',
      chauffeurBenefit1: 'Manage your schedule: slots, availability and a clear overview.',
      chauffeurBenefit2: 'Manage your fleet: vehicles, teams and day-to-day operations.',
      chauffeurBenefit3: 'Track spending and revenue: indicators and summaries in one place.',
      destinationSpotlightBack: 'Back',
      destinationSpotlightFlightTitle: 'Flight times (indicative)',
      destinationSpotlightLead:
        'Get an estimate and book in a few taps. Partner drivers cover the whole island.',
      destinationSpotlightCta: 'See prices and book',
      destinationSpotlightBadge: 'Popular places',
      destinationSpotlightContextTitle: 'For your trip',
      clientNextRideAria: 'Next scheduled ride',
      clientNextRideLabel: 'Next ride',
      clientNextRideLink: 'Account',
      clientLiveMeetCta: 'Join your driver',
      clientTopbarRidesAria: 'Rides and pickup',
      chauffeurLandingHeadlineLead: 'Built to save you time,',
      chauffeurLandingHeadlineAccent: 'Palto is the driver platform for Réunion.',
      chauffeurLandingSub:
        'Scheduling, rides and revenue in one place. Moto-taxi, ride-hail, delivery: stay focused on the road.',
      chauffeurLandingCtaSignup: 'Sign up',
      chauffeurLandingCtaSignin: 'Sign in',
      chauffeurLandingLinkPassengers: 'Passenger home',
      chauffeurLandingLinkBook: 'Book a ride',
      chauffeurLandingTrusted: 'Built for road professionals',
      chauffeurLandingFeaturePlanningTitle: 'Your day, made clear',
      chauffeurLandingFeaturePlanningBody:
        'Slots, requests and statuses: what matters without the noise.',
      chauffeurLandingFeatureFleetTitle: 'Fleet and team',
      chauffeurLandingFeatureFleetBody:
        'Vehicles, teammates and ops as you scale.',
      chauffeurLandingFeatureMoneyTitle: 'Revenue and spend',
      chauffeurLandingFeatureMoneyBody:
        'Simple indicators to track rides and business over time.',
      chauffeurLandingMockCaption: 'Dashboard preview',
      chauffeurLandingMockTask1: 'Ride Le Port → Saint-Denis',
      chauffeurLandingMockTask2: 'Insurance document to renew',
      chauffeurLandingMockTask3: 'Weekly revenue summary',
      chauffeurLandingMockPillLive: 'In progress',
      chauffeurLandingMockPillAction: 'Action',
      chauffeurLandingMockPillStats: 'Stats',
      chauffeurLandingTrustedTag1: 'Réunion Island',
      chauffeurLandingTrustedTag2: 'Moto-taxi',
      chauffeurLandingTrustedTag3: 'Ride-hail',
      chauffeurLandingTrustedTag4: 'Delivery',
      chauffeurLandingMatchEyebrow: 'No more messenger noise',
      chauffeurLandingMatchTitle: 'Clear handoffs from first ping to drop-off.',
      chauffeurLandingMatchLead:
        'Palto connects passengers and drivers around the ride: status, places and what matters in one place. Stop juggling WhatsApp, Messenger and texts.',
      chauffeurLandingMatchPoint1:
        'Structured requests: who, where, when and how to pay — without endless chat threads.',
      chauffeurLandingMatchPoint2:
        'Everyone sees the same source of truth: fewer mix-ups, fewer “what did you say again?”.',
      chauffeurLandingMatchPoint3:
        'You focus on driving and service; Palto carries the business context.',
      chauffeurLandingPlanningBadge: 'Built-in scheduling',
      chauffeurLandingPlanningTitle: 'Your day, visible at a glance',
      chauffeurLandingPlanningBody:
        'Slots, upcoming rides and availability in one view. Plan ahead without a separate calendar or reminders lost in chat apps.',
      chauffeurLandingMatchVisualCaption: 'One professional thread',
      chauffeurLandingClosingTitle: 'Drive with Palto.',
      chauffeurLandingClosingSub: 'Create your driver account and open the dashboard.',
    },
    search: {
      destinationPlaceholder: 'Enter your destination',
      bookingSearch: 'Search',
      bookingSearchLoading: 'Searching…',
      bookingReserve: 'Book',
      bookingReserveLoading: 'Booking…',
      bookingHintScheduled:
        'Enter pickup, destination and time, then tap Book to see your summary.',
      bookingRecapConfirmScheduled: 'Complete booking',
      checkoutTitle: 'Ride payment',
      checkoutLead: 'Review your trip summary, then confirm your booking.',
      checkoutLoggedInAs: 'Passenger account: {email}',
      checkoutStepsAria: 'Booking steps',
      checkoutStepInfo: 'Details',
      checkoutStepCard: 'Card (test)',
      checkoutStripeLead:
        'Card authorization with no immediate charge. Palto charges {fee} € + driver fare at trip end. Quick cancel: no fee.',
      checkoutStripeOff: 'Online payment not configured: pay the driver directly.',
      checkoutNameLabel: 'Name (optional)',
      checkoutNamePlaceholder: 'Your name',
      checkoutEmailLabel: 'Email for updates',
      checkoutEmailPlaceholder: 'you@example.com',
      checkoutCommentLabel: 'Note for driver (optional)',
      checkoutCommentPlaceholder: 'E.g. building entrance behind the post office.',
      checkoutCardLead: 'Enter a Stripe test card below (test mode, no real charge).',
      checkoutAuthorizeCta: 'Authorize payment on card',
      checkoutContinuePayment: 'Continue to payment',
      checkoutPreparing: 'Preparing…',
      checkoutConfirmOrder: 'Confirm booking',
      checkoutDriverLabel: 'Driver:',
      checkoutDriverLater: 'To be assigned',
      checkoutVehicleLabel: 'Vehicle:',
      checkoutDriverFare: 'Driver fare (incl. tax):',
      checkoutPaltoFee: 'Palto fee:',
      checkoutTotalAuth: 'Total authorized on card:',
      checkoutTotalEstimate: 'Estimated total:',
      checkoutTestCardAria: 'Stripe test card',
      checkoutTestCardTitle: 'Test mode — fake card',
      checkoutTestCardLead: 'No real money is charged. Use this card in the field below:',
      checkoutTestCardCopy: 'Copy number',
      checkoutTestCardCopied: 'Copied',
      checkoutTestCardExpiry: 'Expiry: any future date (e.g. 12/34)',
      checkoutTestCardCvc: 'CVC: any 3 digits (e.g. 123)',
      goTimingNow: 'Leave now',
      goTimingLater: 'Schedule pickup',
      goTimingPickerTitle: 'When do you leave?',
      goTimingPickerCloseAria: 'Close',
      popularPlacesTitle: 'Most requested places',
      sectorsTitle: 'On the island',
      chooseRideTitle: 'Choose a ride',
      chooseRideSubtitle: 'Estimated time and distance for each driver.',
      chooseRideRadiusLead: 'Drivers available within {km} km of your pickup.',
      editRideQuery: 'Edit trip',
      goPreviousStep: 'Back',
      chooseDriverCta: 'Choose this driver',
      chooseDriverHint: 'Select a driver to continue',
      driversLoading: 'Searching for online drivers…',
      driversEmpty:
        'No drivers available in this radius. A driver’s position stays visible for about 2 hours after their last update (dashboard or “Refresh my location”).',
    },
    chauffeurAuth: {
      titleLogin: 'Driver sign in',
      titleSignup: 'Create a driver account',
      subtitleLogin: 'Open your dashboard, rides and fleet tools.',
      subtitleSignup:
        'After signup, rides stay blocked until the legal documents listed in the dashboard are provided (checkboxes on this device). Phone, vehicle type and delivery equipment are stored on this device.',
      signupPhoneLabel: 'Phone',
      signupPhoneDial: 'Country code',
      signupPhonePlaceholder: 'e.g. 692 12 34 56',
      vehicleTypeLabel: 'Vehicle type',
      vehicleBerline: 'Sedan',
      vehicleUtilitaire: 'Van / utility',
      vehicleMoto: 'Motorcycle',
      vehicleScooter: 'Scooter',
      deliveryEquippedLabel: 'I am equipped for deliveries',
      deliveryEquippedHint: '(insulated box, straps, etc.)',
      errorPhoneInvalid: 'Invalid phone number for the selected country code.',
      errorPhoneRequired: 'Phone number is required.',
      tabLogin: 'Sign in',
      tabSignup: 'Create account',
      email: 'Email',
      password: 'Password',
      confirmPassword: 'Confirm password',
      submitLogin: 'Sign in',
      submitSignup: 'Create account and sign in',
      submittingLogin: 'Signing in…',
      submittingSignup: 'Creating…',
      switchToSignup: 'No account yet? Create one',
      switchToLogin: 'Already have an account? Sign in',
      backToSite: 'Back to site',
      footerLegal:
        'By continuing you acknowledge Palto’s terms of use and privacy policy.',
      errorGeneric: 'Something went wrong. Please try again.',
      errorEmailUsed: 'This email is already registered on this device.',
      errorEmailReserved:
        'This email is reserved for the primary admin account — use Sign in or pick another email.',
      errorPasswordShort: 'Password must be at least 6 characters.',
      errorPasswordMismatch: 'Passwords do not match.',
      errorInvalidEmail: 'Invalid email address.',
    },
    chauffeurCompliance: {
      bannerTitle: 'Legal documents required',
      bannerLead:
        'As a driver registered on this device, you must provide the items below before accepting or starting rides. Tick each line once the proof is submitted (local simulation).',
      checklistLead: 'Tick each document once provided (real checks to be wired server-side).',
      checklistAria: 'Mandatory documents list',
      allProvided: 'All documents are marked as provided — rides are unlocked.',
      complianceUploadHint:
        'No file is uploaded here; secure KYC / upload integration is planned for production.',
      doc_driving_license: 'Driving licence (appropriate category)',
      doc_vtc_or_goods_capacity:
        'Professional VTC card or right to operate — or goods transport capacity certificate',
      doc_digital_identity: 'Digital identity / official ID document',
      doc_kbis_siret: 'KBIS or SIRET number (company / sole trader)',
      doc_security_declaration: 'Safety / registry proof (depending on your status)',
      doc_rc_pro: 'Professional liability insurance (RC Pro)',
      doc_insurance_civil_pro: 'Civil and professional insurance certificates',
      doc_vehicle_insurance: 'Insurance for the vehicle used',
    },
    clientAuth: {
      titleLogin: 'Passenger sign in',
      titleSignup: 'Create a passenger account',
      subtitleLogin: 'Access your account, rides and preferences.',
      subtitleSignup:
        'Account is stored on this device. Your “My account” data stays local in this browser.',
      tabLogin: 'Sign in',
      tabSignup: 'Create account',
      email: 'Email',
      password: 'Password',
      confirmPassword: 'Confirm password',
      submitLogin: 'Sign in',
      submitSignup: 'Create account and sign in',
      submittingLogin: 'Signing in…',
      submittingSignup: 'Creating…',
      switchToSignup: 'No account yet? Create one',
      switchToLogin: 'Already have an account? Sign in',
      backToSite: 'Back to site',
      footerLegal:
        'By continuing you acknowledge Palto’s terms of use and privacy policy.',
      errorGeneric: 'Something went wrong. Please try again.',
      errorEmailUsed: 'This email is already registered on this device.',
      errorEmailReserved:
        'This email is reserved for the main passenger account — use Sign in or another email.',
      errorPasswordShort: 'Password must be at least 6 characters.',
      errorPasswordMismatch: 'Passwords do not match.',
      errorInvalidEmail: 'Invalid email address.',
    },
    error: {
      pageNotFound: 'Page not found',
      pageNotFoundMessage: 'The page you are looking for does not exist or has been moved.',
      backToHome: 'Back to home',
      discoverProjects: 'Book a ride',
    },
    project: {
      context:
        'Go is Palto’s booking UI: pickup and drop-off on Réunion, interactive map, time and distance estimates, immediate or scheduled ride, then confirmation.',
      objectives: 'Product goals',
      team: 'Stakeholders',
      myRole: 'UI role',
      role: 'ROLE',
      name: 'LABEL',
      tocSummary: 'Overview',
      tocTeam: 'Stakeholders',
      caseStudie: 'Journey & interface',
      ideation: 'Flows explored',
      implementation: 'Integration & stack',
      results: 'Tracking & next steps',
      problematique: 'User need',
      solution: 'Palto response',
      process: 'Approach',
      processIntro:
        'The flow was framed around real island trips, traffic constraints, and clarity between on-demand and scheduled rides.',
      processSummary:
        'Prototype iterations: address search, nearby drivers, route polyline, and validation steps before sending the ride request.',
      audit: 'Research & usage',
      architecture: 'Functional architecture',
      userFlow: 'User journey',
      designSystem: 'UI system',
      dsTabCarousel: 'Description',
      dsTabPalette: 'Palette',
      dsTabTypescale: 'Type scale',
      palette: 'Palette',
      materialDesign: '(Material Design)',
      roleToken: 'Role (Token)',
      usage: 'Usage / Function',
      hexValue: 'Hex value',
      typescale: 'Typescale',
      baseValue: 'Base Value: 16',
      roleCol: 'Role',
      typography: 'Typography',
      size: 'Size',
      lineHeight: 'Line height',
      example: 'Example',
      conception: 'Design & iterations',
      integration: 'Integration & rollout',
      otherProjects: 'Continue on Palto',
      whatNext: 'Next steps',
      backToTop: 'Back to top',
      backHome: 'Back home',
      viewProject: 'View Go details',
      contactMe: 'Contact us',
      auditLead:
        'Local mobility research: precise pickup, timing hesitation, need for map + text cues for drop-off, and fast reading on phones.',
      auditBody:
        'Useful patterns: readable forms, address suggestions, explicit loading states, actionable errors, and a clear recap before confirmation.',
      archLead:
        'Ride-first model: origin, destination, time window, status (draft / requested / accepted), linked driver, mapping estimates for time and distance.',
      archBody:
        'Screens separate concerns: address entry, map and route, mode choice (now / later), driver step, then submit — to ease API evolution.',
      conceptionLead1:
        'Mobile-first readability: stronger contrast, comfortable tap targets, short labels on key steps.',
      conceptionLead2:
        'Several iterations on the booking path to reduce back-and-forth between map, address fields, and recap.',
      conceptionCaption1:
        'A light top bar: home, contact, account, and driver access — without distracting from booking.',
      conceptionCaption2:
        'Primary actions stay near the form: search route, choose ride mode, move to the next step.',
      conceptionCaption3:
        'Palto brand aligned with readability over the map and light / dark themes.',
      conceptionCaption4:
        'Color and text pairs checked on cards and status chips; typography hierarchy separates estimate, indicative fare, and primary action.',
      contrastTitle: 'Readability & contrast check',
      contrastImageAlt: 'Go — booking UI, light mode',
      lightModeSinglePageAlt: 'Go — journey recap',
      lightModeSetp1Alt: 'Go — driver choice, step 1',
      integrationTitle:
        'Progressive rollout: the UI evolves smoothly; enabling the API + Supabase persists rides and driver actions.',
      integrationLead:
        'Isolated building blocks (map, driver list, recap) so business rules, off-line payment for now, then notifications, can evolve cleanly.',
      december2023: 'Research & framing',
      february2025: 'Go UI stabilized',
      auditAlt1: 'Usage — local mobility 1',
      auditAlt2: 'Usage — local mobility 2',
      auditAlt3: 'Usage — local mobility 3',
      auditAlt4: 'Usage — local mobility 4',
      conceptGraduationLabel: 'Step {n}',
      conceptionGraduationGroup: 'Booking journey',
      conceptionStageAlt: 'Step {concept} — screen {slide}',
      conceptionVerticalCarousel: 'Screens for the selected step',
      cardSwapAria: 'Animated preview — Palto Go journey',
      integrationAlt: 'Technical integration',
      wireframeAlt: 'Wireframe — Palto booking flow',
      maquetteAlt: 'Mockup — Palto booking screen',
      axisHorizontal: 'Horizontal axis',
      axisVertical: 'Vertical axis',
    },
    driverDashboard: {
      titleOverview: 'Overview',
      titleCourses: 'Rides',
      titleStats: 'Statistics',
      titleClients: 'Clients',
      titlePlanning: 'Schedule',
      titleUser: 'Driver account',
      titleSettings: 'Settings',
      titleHelp: 'Help',
      navOverview: 'Overview',
      navCourses: 'Rides',
      navStats: 'Statistics',
      navClients: 'Clients',
      navPlanning: 'Schedule',
      navUser: 'Account',
      navSettings: 'Settings',
      navHelp: 'Help',
      navOrganization: 'Organization',
      titleOrganization: 'My organization',
      helpLead: 'Shortcuts and common answers for the driver dashboard.',
      settingsMoreHint:
        'These preferences match the passenger site account: they apply to all of Palto on this device.',
      mainSubtitle: 'Your rides, schedule and operations in one place.',
      statsSubtitle: 'A quick, readable view of your driver activity.',
      statsHeatmapPlaceholder:
        'The yearly heatmap and summaries (busiest day, streaks) will show when the statistics API is connected. The KPI cards above still reflect your local rides.',
      orgPageLead:
        'Manage your fleet on this device. Invitations are simulated — API integration planned later.',
      orgFleetCode: 'Fleet code',
      orgBase: 'Base',
      orgAdminEmail: 'Administrator',
      orgCreated: 'Created on',
      orgMembersTitle: 'Members',
      orgInviteLabel: 'Invite a driver (email)',
      orgInvitePlaceholder: 'driver@example.com',
      orgInviteButton: 'Send invitation',
      orgInviteInvalid: 'Please enter a valid email address.',
      orgInviteDuplicate: 'This address is already invited or is a member.',
      orgInviteSelf: 'You cannot invite yourself.',
      orgStatusPending: 'Invitation sent',
      orgStatusActive: 'Active',
      orgRoleAdmin: 'Administrator',
      orgRoleDriver: 'Driver',
      orgRemoveInvite: 'Remove',
      orgDeleteOrg: 'Delete organization',
      orgDeleteConfirm:
        'Delete this organization? Local data will be cleared and the sidebar entry will disappear.',
      orgSectionTitle: 'Organization',
      orgNoOrgHint:
        'Create an organization to become admin, get a fleet code, and invite other drivers. The “Organization” item will appear in the sidebar.',
      orgNoOrgSoonLabel: 'Coming soon',
      orgCreateName: 'Organization name',
      orgCreateBase: 'Base / area',
      orgCreateButton: 'Create organization',
      orgOpenOrganization: 'Open Organization page',
      orgNameRequired: 'Organization name is required.',
      orgModeOrgLabel: 'Fleet',
      orgNavTeam: 'Team',
      orgNavFleet: 'Fleet',
      orgNavInvites: 'Invitations',
      orgNavSettings: 'Settings',
      orgProfileCoverAlt: 'Fleet cover image',
      orgProfileLogoAlt: 'Fleet logo',
      orgProfileImportantTitle: 'Key information',
      orgProfileDriversLabel: 'Active drivers',
      orgProfileRatingLabel: 'Average rating',
      orgProfileRatingSuffix: 'reviews',
      orgProfileReviewsTitle: 'Latest reviews',
      orgProfileReviewsLead: 'Illustrative samples — connect real customer reviews later.',
      orgProfileReview1Author: 'Marie L.',
      orgProfileReview1Body:
        'Driver on time, smooth ride. I recommend this fleet for city trips.',
      orgProfileReview2Author: 'Karim D.',
      orgProfileReview2Body: 'Very professional; clear SMS updates for my medical appointment.',
      orgProfileReview3Author: 'Sophie P.',
      orgProfileReview3Body: 'Great for the airport: clean car, smooth driving, help with luggage.',
      orgReviewsPrev: 'Previous review',
      orgReviewsNext: 'Next review',
      orgReviewsDots: 'Review navigation',
      orgReviewsGoTo: 'Go to review {n}',
      orgInviteNotifTitle: 'Fleet invite · {org}',
      orgInviteNotifDesc: 'Fleet code {code} · Invited by {from}. Join from your account.',
      notificationsModalTitle: 'All notifications',
      notificationsSeeAll: 'See all',
      moreMenuAria: 'More options',
      moreMenuTitle: 'Options',
      reportBug: 'Report a bug',
      bugModalTitle: 'Report a bug',
      bugModalLead:
        'Use thumbs up or down to say if this screen feels fine or blocking, then describe the issue.',
      bugSentimentLabel: 'How this screen feels',
      bugMessageLabel: 'Bug description',
      bugMessagePlaceholder: 'Steps to reproduce, error message, browser…',
      bugSubmit: 'Send',
      bugSubmitting: 'Sending…',
      bugClose: 'Close',
      bugToastOk: 'Report sent. Thank you!',
      bugToastErr: 'Could not send. Please try again later.',
      bugValidation: 'Please describe the issue before sending.',
      bugEmailMissing: 'Add an email to your driver profile to send a report.',
      orgSettingsDangerLead:
        'Sensitive area: deleting removes fleet data, members, and invitations stored on this device.',
      fleetTitle: 'Fleet management',
      fleetLead:
        'Sectors (West, South, East, North, Cilaos, etc.), vehicles, and availability — local data on this device. Connect to your back office or API later.',
      fleetFilterLabel: 'Filter by sector',
      fleetFilterAll: 'All sectors',
      fleetSummaryTitle: 'Active drivers by sector',
      fleetColMember: 'Member',
      fleetColVehicle: 'License plate',
      fleetColModel: 'Vehicle',
      fleetColZone: 'Sector',
      fleetColAvail: 'Status',
      fleetHintPending: 'Pending invite — full assignment once the account joins.',
      fleetPlatePlaceholder: 'e.g. AB-123-CD',
      fleetModelPlaceholder: 'e.g. Sedan, scooter…',
      fleetDuplicatePlate: 'This plate is already assigned to another active member.',
      fleetZoneUnset: 'Unassigned',
      fleetZoneWest: 'West',
      fleetZoneSouth: 'South',
      fleetZoneEast: 'East',
      fleetZoneNorth: 'North',
      fleetZoneCilaos: 'Cilaos',
      fleetZoneCircus: 'Cirques',
      fleetZonePlainCafres: 'Plaine des Cafres',
      fleetZoneStPaul: 'Saint-Paul',
      fleetAvailAvailable: 'Available',
      fleetAvailOnCourse: 'On a ride',
      fleetAvailPause: 'Break',
      fleetAvailOff: 'Off duty',
    },
    clientAccount: {
      title: 'My account',
      lead: 'Information used for your rides and contact with Palto drivers. Data stored on this device.',
      navOverview: 'Overview',
      navPersonalInfo: 'Personal information',
      navSecurity: 'Security',
      navPrivacy: 'Privacy and data',
      navSettings: 'Settings',
      navHelp: 'Help',
      navBackSite: 'Back to site',
      navBackOverview: 'Back',
      navBackOverviewAria: 'Back to account overview',
      navSignOut: 'Sign out',
      sectionPlaceholder: 'Content for this section will be added later.',
      expandNav: 'Expand navigation',
      collapseNav: 'Collapse navigation',
      closeMenu: 'Close menu',
      openMenu: 'Open menu',
      mobileActions: 'Account actions',
      profileSection: 'Client profile',
      edit: 'Edit',
      photoAlt: 'Profile photo',
      changeProfilePhotoAria: 'Change profile photo',
      photoReadError: 'Could not read this image. Try another file (JPEG or PNG).',
      photoStorageError:
        'Could not save (storage full). Try a smaller image or free space on this device.',
      statusActive: 'Active',
      firstName: 'First name',
      lastName: 'Last name',
      email: 'Email',
      phone: 'Phone',
      city: 'City',
      status: 'Status',
      preferenceTitle: 'Payment preference',
      preferenceHint: 'How you prefer to pay; the driver may suggest an alternative depending on the ride.',
      prefIndifferent: 'No preference',
      prefCard: 'Card',
      prefCash: 'Cash',
      save: 'Save',
      cancel: 'Cancel',
      recentTitle: 'Recent rides',
      recentRidesCaption: 'Local history on this device.',
      bookRide: 'Book a ride',
      rideDetailTitle: 'Ride summary',
      rideDetailClose: 'Close',
      rideDepart: 'Pickup',
      rideArrive: 'Drop-off',
      rideDate: 'Date',
      rideDepartTime: 'Pickup time',
      rideArriveTime: 'Estimated arrival',
      rideDuration: 'Duration',
      rideDistance: 'Distance',
      ridePrice: 'Fare',
      rideDriver: 'Driver',
      rideVehicle: 'Vehicle',
      ridePayment: 'Payment',
      rideReference: 'Reference',
      rideStatus: 'Status',
      rideDurationMinutes: '{n} min',
      rideDistanceKm: '{n} km',
      ridePriceEur: '€{n}',
      rideMeetTitle: 'Your driver is waiting',
      rideMeetLead:
        'Go to the pickup point below. Identify the vehicle using the model, colour and licence plate.',
      rideMeetPickup: 'Pickup location',
      rideMeetPickupTime: 'Pickup around',
      rideMeetVehicleColor: 'Colour:',
      rideMeetCall: 'Call driver',
      rideMeetCallDisabledHint: 'Unavailable for now',
      rideMeetCta: 'I am with my driver',
      rideMeetConfirmed: 'Noted',
      rideMeetToast: 'Thanks! Have a good ride with Palto.',
      rideMeetDriverCardAria: 'Driver and vehicle details',
      rideMeetLocationTitle: 'Driver location',
      rideMeetLocationLive: 'Live',
      rideMeetLocationAria: 'Driver location relative to pickup',
      rideMeetDistanceMeters: '≈ {m} m from pickup',
      rideMeetMapNoToken:
        'If mapping service is unavailable, the map is hidden here. Distance still updates.',
      rideMeetDriverPin: 'Driver',
      rideMeetClientPin: 'You',
      rideEndTitle: 'End of ride',
      rideEndLead: 'Ride {route} with {driver}. Check the fare, time and distance, then leave a review.',
      rideEndStatsAria: 'Fare, distance and trip duration',
      rideEndCashTitle: 'Cash payment',
      rideEndCashHint:
        'For now only cash payment is supported on this screen. Exact change helps when possible.',
      rideEndCashConfirm: 'I confirm I paid {amount} to the driver in cash.',
      rideEndReviewTitle: 'Your review',
      rideEndReviewHint: 'Rating and comment are simulated; nothing is sent to a server yet.',
      rideEndStarsAria: 'Rating out of 5',
      rideEndStarLabel: 'Rate {n} out of 5',
      rideEndCommentLabel: 'Comment (optional)',
      rideEndCommentPlaceholder: 'Pickup experience, driving, punctuality…',
      rideEndSubmit: 'Send review',
      rideEndThanks: 'Thanks for your feedback!',
      personalHint: 'Update your details below, then save.',
      overviewProfileHint:
        'To change your details or photo, use Personal information in the menu.',
      overviewCoursesHint:
        'The full list of your rides is under the Courses tab in the menu.',
      navCourses: 'Rides',
      navPlaces: 'Saved places',
      navWallet: 'Wallet',
      walletLead:
        'View your balance and activity history. Amounts are stored locally on this device (no real payments).',
      walletBalanceTitle: 'Available balance',
      walletActivityNote:
        'The movements below are fictional; only the balance can change using the simulated top-up.',
      walletMovementsTitle: 'Recent activity',
      walletSimulateTopup: 'Simulate top-up (+€5.00)',
      walletMov1: 'Ride · Le Port → Saint-Denis',
      walletMov2: 'Wallet top-up (simulation)',
      walletMov3: 'Ride · Saint-Pierre → Étang-Salé',
      walletOpen: 'Manage wallet',
      overviewWalletHint: 'Current balance: {balance}. Top-ups and details in the Wallet tab.',
      coursesRecapTitle: 'All your rides',
      coursesRecapLead: 'Every ride stored on this device.',
      coursesEmptyHint: "You haven't ordered a ride yet.",
      securityPasswordTitle: 'Password',
      securityPasswordField: 'Current password',
      securityLastChanged: 'Last changed on {date}',
      securityChangePassword: 'Change password',
      securityNewPassword: 'New password',
      securityConfirmPassword: 'Confirm password',
      securitySavePassword: 'Save new password',
      securityCancel: 'Cancel',
      securityPasswordMismatch: 'Passwords do not match.',
      securityPasswordTooShort: 'At least 8 characters.',
      securityOAuthTitle: 'Social sign-in',
      securityOAuthGoogle: 'Google',
      securityOAuthFacebook: 'Facebook',
      securityOAuthApple: 'Apple',
      securityOAuthConnect: 'Connect',
      securityOAuthDisconnect: 'Disconnect',
      securityOAuthConnected: 'Connected',
      securityOAuthNotConnected: 'Not connected',
      settingsLead: 'Adjust how the app behaves on this device.',
      settingsLanguageTitle: 'Language',
      settingsLanguageHint: 'Choose the language for account and site copy.',
      settingsAppearanceTitle: 'Appearance',
      settingsAppearanceHint:
        'Dark mode applies the site-wide palette (data-app-theme on the document root).',
      settingsDarkMode: 'Dark mode',
      settingsTextSizeTitle: 'Text size',
      settingsTextSizeHint:
        '100% is the usual site size. Move the slider right to enlarge the whole UI (including pixel-sized text). You cannot shrink below normal. Saved on this device.',
      settingsTextSizeAria: 'Site text size',
      settingsTextSizeValue: '{n}%',
      settingsNotificationsTitle: 'Notifications',
      settingsNotificationsHint:
        'Channels for ride reminders and messages (nothing is sent yet; preferences stored on this device).',
      settingsNotifyEmail: 'Email',
      settingsNotifySms: 'SMS',
      settingsNotifyPush: 'Push notifications',
      settingsMoreHint: 'Additional controls (accessibility, etc.) can be added here later.',
      helpLead: 'Frequently asked questions and where to get support.',
      helpFaq1Q: 'How is my account data stored?',
      helpFaq1A:
        'Profile, security, and wallet data are stored locally in your browser. These screens are not synced to a server.',
      helpFaq2Q: 'How do I view my rides?',
      helpFaq2A:
        'Open the Rides tab, then tap a row for the full summary. Listed rides are fictional sample data.',
      helpFaq3Q: 'Is the wallet balance real?',
      helpFaq3A:
        'No — it is a local simulation only. “Simulate top-up” increases the fictional balance on this device.',
      helpContactHint: 'To reach us, use the Palto Contact page from the home menu or footer.',
      placesLead:
        'Save your usual addresses to fill pickup or drop-off faster. Data is stored on this device.',
      placesHome: 'Home',
      placesWork: 'Work',
      placesAddressLabel: 'Address',
      placesAddressPlaceholder: 'Street, neighbourhood, city…',
      placesExtrasTitle: 'Other places',
      placesExtraLabel: 'Place name',
      placesAddExtra: 'Add a place',
      placesRemoveExtra: 'Remove',
      placesSave: 'Save places',
      placesOverviewHint: 'Home, work, and favourites for your next rides.',
      placesOverviewOpen: 'Manage places',
      placesNoExtras: 'No extra places yet. Use “Add a place” for favourites (e.g. gym, family).',
      placesSuggestionsAria: 'Address suggestions',
      placesSuggestionsPopular: 'Popular places',
      placesSuggestionsAddresses: 'Addresses (search)',
      placesSuggestionsLoading: 'Searching…',
      placesSuggestionsMinChars: 'Type at least 3 characters to get suggestions.',
      placesSuggestionsEmpty: 'No address found.',
      placesMarkOnMap: 'Mark on map',
      placesCoordsSaved: 'Location saved',
      placesNoMapToken: 'Map and suggestions unavailable (mapping service unavailable).',
      placesMapModalTitle: 'Pick on the map',
      placesMapModalHint: 'Tap the map to move the pin to the nearest road, then confirm.',
      placesMapConfirm: 'Save this location',
      placesMapCancel: 'Cancel',
      placesOutsideReunion: 'Choose a point on Réunion Island.',
      placesMapSnapFail: 'Could not snap to a road (try closer to a road).',
      placesGeocodeError: 'Could not read the address. Try again.',
      placesMapConfirming: 'Saving…',
    },
  },
}
